# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3acdbf574a038deacef9b8fd0acbb6e5079c8d1482e88724a02b05d75bdef12e199a9639508beaeb547084c4501976af3cc33fbabb4d03127ffd71efbcf746b8

test:
  secret_key_base: c487080e8e2f35b4ebb9334bbe40bfde9e339d6a19e35cfc1e73a3a5eec0b69f1d6176a9086ff2a6366b9dc29471eaf036bfdfb4bcae89f5df1fe1c3bf00462a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
